# app metadata used for building packages


os:
  Ubuntu:
    packages:
      - python2.7
    script: # execute on every package
      - sudo apt-get update
    bootstrap: # executed on fresh package
      - bla bla
     12.04:
      packages:
        - python3.2


interpreter:
  type: python|ruby|php
  # will use highest compatible version
  versions:
    - 1.9.3
    - 1.8.7


repository:
  env:
    MYENV: value
  clone: git clone $source_address %destination%
  update:
    - git reset --hard
    - git pull
  info: git log -n 1
  changelog: git log --no-merges %old%..%new%"


env: # env variables set for running app
  MYENV: value


actions:
  env: # env variables used while executing actions
    MYENV: value
  setup: # app setup on builder
    before:
    main:
    after:
