# app metadata used for building packages


os:
  ubuntu:
    packages:
      - python2.7
    script: # executed on fresh package
      - bla bla


interpreter:
  type: python|ruby|php
  # will use highest compatible version
  versions:
    - 1.9.3
    - 1.8.7


actions:
  setup: # app setup on builder
    before:
    main:
    after:
