#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    :copyright: Copyright 2013 by Łukasz Mierzwa
    :contact: l.mierzwa@gmail.com
"""


import os

from plumbum import cli

from upaas.config.base import ConfigurationError
from upaas.cli.base import UPaaSApplication
from upaas.config.metadata import MetadataConfig

from upaas_builder import __version__ as UPAAS_VERSION
from upaas_builder import exceptions
from upaas_builder.builder import Builder


class ExitCodes:
    ok = 0
    config_error = 1
    metadata_error = 2
    not_root = 3


class BuilderApplication(UPaaSApplication):

    VERSION = UPAAS_VERSION

    fresh = cli.Flag(["f", "force-fresh"], help="Force building fresh package")

    @cli.switch(["c", "config"], str, help="Configuration file path",
                mandatory=True)
    def set_config_path(self, path):
        self.config_path = path

    def root_check(self):
        if os.geteuid() != 0:
            self.log.error(u"%s must be run as root user" % self.PROGNAME)
            return ExitCodes.not_root

    def main(self, metadata):
        self.setup_logger()
        self.root_check()

        try:
            self.metadata = MetadataConfig.from_file(metadata)
        except ConfigurationError:
            self.log.error(u"Invalid metadata, aborting")
            return ExitCodes.metadata_error

        try:
            self.builder = Builder(self.config_path, self.metadata)
        except exceptions.InvalidConfiguration:
            self.log.error(u"Invalid configuration, aborting")
            return ExitCodes.config_error

        self.log.info(u"Building package from '%s'" % metadata)
        self.builder.build_package(force_fresh=self.fresh)


if __name__ == "__main__":
    BuilderApplication.run()
